snort:
  image: vimagick/snort
  command: -q -c /etc/snort/snort.conf -A console -k none -i ens3
  volumes:
    - ./data/snort.conf:/etc/snort/snort.conf
    - ./data/rules:/etc/snort/rules
    - ./data/log:/var/log/snort
  cap_add:
    - NET_ADMIN
  net: host
  tty: true
  restart: unless-stopped
