prestashop:
  image: vimagick/prestashop
  ports:
    - "8000:80"
  links:
    - mysql
  volumes:
    - /var/www
  restart: always

mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=prestashop
  restart: always
