drone:
  image: drone/drone
  ports:
    - "8000:8000"
  volumes:
    - ./drone:/var/lib/drone
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - REMOTE_DRIVER=gogs
    - REMOTE_CONFIG=https://git.easypi.info/?open=false
    - DEBUG=true
  restart: always
