ot-recorder:
  image: vimagick/ot-recorder
  ports:
    - "8083:8083"
  volumes:
    - ./data:/var/spool/owntracks/recorder/store
  environment:
    - OTR_HOST=iot.eclipse.org
    - OTR_PORT=1883
    - OTR_TOPICS=owntracks/username/#
    - OTR_OPTIONS=--browser-apikey XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  restart: always
