plex:
  image: vimagick/plex
  ports:
    - "32400:32400"
  volumes:
    - "./data:/data:ro"
    - "./data/plex:/var/lib/plexmediaserver/Library/Application Support"
  environment:
    - "HOME=/data"
  working_dir: /data
# user: 1000:1000
  restart: always
