hass:
  image: easypi/hass-arm:debian
  volumes:
    - ./data:/etc/hass
  net: host
  privileged: yes
  restart: unless-stopped

hcfg:
  image: easypi/hcfg-arm
  volumes:
    - ./data:/etc/hass
  net: host
  working_dir: /etc/hass
  restart: unless-stopped
