tinc:
  image: vimagick/tinc
  ports:
    - "655:655/tcp"
    - "655:655/udp"
  volumes:
    - ./tinc:/etc/tinc
  environment:
    - IP_ADDR=45.32.57.113
  cap_add:
    - NET_ADMIN
  dns: 8.8.8.8
  restart: always
