pihole:
  image: pihole/pihole:v4.0_armhf
  ports:
    - 53:53/tcp
    - 53:53/udp
    - 67:67/udp
    - 80:80/tcp
    - 443:443/tcp
  volumes:
    - ./data/pihole:/etc/pihole
    - ./data/dnsmasq.d:/etc/dnsmasq.d
  environment:
    - ServerIP=192.168.31.195
    - WEBPASSWORD=random
    - DNS1=8.8.8.8
    - DNS2=8.8.4.4
  cap_add:
    - NET_ADMIN
  restart: unless-stopped
