zookeeper:
  image: easypi/zookeeper-arm
  ports:
    - "2181:2181"
  volumes:
    - ./data/zookeeper/data:/data
    - ./data/zookeeper/datalog:/datalog
  restart: always

kafka:
  image: easypi/kafka-arm
  ports:
    - "9092:9092"
  hostname: kafka
  volumes:
    - ./data/kafka:/kafka
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    - KAFKA_ADVERTISED_HOST_NAME=kafka
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  links:
    - zookeeper
  restart: always
