coordinator:
  image: vimagick/presto
  ports:
    - "8080:8080"
  volumes:
    - ./conf/coordinator:/opt/presto/etc
    - ./data/coordinator:/var/lib/presto
  restart: always

worker1:
  image: vimagick/presto
  ports:
    - "8081:8080"
  volumes:
    - ./conf/worker1:/opt/presto/etc
    - ./data/worker1:/var/lib/presto
  links:
    - coordinator
  restart: always
