data:
  image: busybox
  volumes:
    - /etc/openvpn

server:
  image: vimagick/openvpn
  expose:
    - "1194/tcp"
  volumes_from:
    - data
  cap_add:
    - NET_ADMIN
  restart: always

stunnel:
  image: vimagick/stunnel
  ports:
    - "4911:4911"
  links:
    - server
  environment:
    - CLIENT=no
    - SERVICE=openvpn
    - ACCEPT=0.0.0.0:4911
    - CONNECT=server:1194
  restart: always
