gogs:
  image: easypi/gogs-arm
  ports:
    - "2222:22"
    - "3000:3000"
  volumes:
    - ./data:/data
  links:
    - mysql
  restart: always

mysql
  image: easypi/mariadb-arm
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=gogs
  restart: always

phpmyadmin:
  image: easypi/phpmyadmin-arm
  ports:
    - "8080:80"
  environment:
    - PMA_HOST=mysql
    - PMA_PORT=3306
  links:
    - mysql
  restart: always
