pptpd:
  image: vimagick/pptpd
  volumes:
    - ./pptpd.conf:/etc/pptpd.conf
    - ./options.pptp:/etc/ppp/options.pptp
    - ./chap-secrets:/etc/ppp/chap-secrets
  net: host
  privileged: true
  restart: always
