version: '2'

services:
  drone-server:
    image: quay.io/armswarm/drone:0.8
    ports:
      -  "8000:8000"
      -  "9000:9000"
    volumes:
      - ./data/drone:/var/lib/drone
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=https://drone.easypi.pro
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=root:root@tcp(mariadb:3306)/drone?parseTime=true
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://gogs.easypi.pro
      - DRONE_SECRET=0123456789
      - DRONE_ADMIN=root
    depends_on:
      - mariadb
      - gogs
    restart: always

  drone-agent:
    image: drone/agent:linux-arm
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=0123456789
    depends_on:
      - drone-server
    restart: always

  mariadb:
    image: easypi/mariadb-arm
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drone
    restart: always

  gogs:
    image: easypi/gogs-arm
    ports:
      - "2222:22"
      - "3000:3000"
    volumes:
      - ./data/gogs:/data
    restart: always

  phpmyadmin:
    image: easypi/phpmyadmin-arm
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    restart: always
