firefox:
  image: selenium/node-firefox
  ports:
    - "5555:5555"
    - "5900:5900"
  environment:
    - JAVA_OPTS=-Xmx512m
    - NODE_MAX_INSTANCES=2
    - NODE_MAX_SESSION=2
    - SE_OPTS=-host 5.6.7.8 -port 5555
    - HUB_PORT_4444_TCP_ADDR=1.2.3.4
    - HUB_PORT_4444_TCP_PORT=4444
  restart: always
